# Generated by Django 4.2.2 on 2023-07-02 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateField(verbose_name=datetime.date(2023, 7, 2)),
        ),
    ]
